### ISSUE TITLE
ERROR in ./node_modules/@wojtekmaj/react-daterange-picker/dist/DateRangePicker.js 14:40-83 Module not found: Error: Can't resolve 'react-date-picker/dist/DateInput' in 'Folder Name\node_modules\@wojtekmaj\react-daterange-picker\dist'

### ISSUE THREAD

**Issue by iconicsudip** [wojtekmaj/react-daterange-picker#303] opened 2023-06-30 07:10 UTC
please help needed ASAP

I am using in my college project

**Comment by wojtekmaj** [comment] 2023-06-30 07:54
Install latest version.

**Comment by wojtekmaj** [comment] 2023-06-30 07:55
Duplicate of #302

**Closed by wojtekmaj** 2023-06-30 07:55 UTC
